#
# Deploy to Azure Container Apps
# 
#

name: CD ACA

on:
  workflow_dispatch:
    inputs:  
        IMAGE_TAG:
          description: "Image tag to be deployed"
          required: true
          default: "21-04-2022.1534"

env:
  # CLUSTER_NAME: srewithazureunai-aks-unai
  LOCATION: westeurope
  ACR_REPO: srewithazureunai.azurecr.io/dotnet6 
  RG: srewithazure
  ACA_NAME: srewithazureunai-containerapp
  # INGRESS_DNS_HOST: dotnet-demoapp.kube.benco.io
  # AD_CLIENT_ID: 3584ac39-1ab1-4fe6-a3dd-4b2fbedc9d7d

jobs:
  #
  # Deploy Azure Container App
  #
  deploy-azure-green:
    name: Deploy Azure Container App to Azure Resource Group
    runs-on: ubuntu-latest
    # environment:
    #   name: AKS
    #output for next job
    outputs:
      LatestRevision: ${{ steps.get-latest-aca-revision.outputs.LatestRevision }}
      FirstDeployment: ${{ steps.first-deployment.outputs.FirstDeployment }}

    steps:

    # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  

      #does the cluster exist, first deployment detect
    - name: Get frist deployment BOOL
      uses: azure/CLI@v1
      id: first-deployment
      with:
        azcliversion: 2.35.0
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          check=$(az containerapp list --query "[?name=='$ACA_NAME']")
          [ "$check"=="[]" ] && $FirstDeployment=false
          echo "FirstDeployment=$FirstDeployment" >> $GITHUB_ENV
          echo "::set-output name=FirstDeployment::$FirstDeployment"

    - name: Get latest ACA REVISION
      uses: azure/CLI@v1
      id: get-latest-aca-revision
      if: steps.first-deployment.outputs.FirstDeployment != false
      with:
        azcliversion: 2.35.0
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          LatestRevision=$(az containerapp revision list -n $ACA_NAME -g $RG --query "[?properties.trafficWeight ==\`100\`][].name" --output tsv)
          echo "LatestRevision=$LatestRevision" >> $GITHUB_ENV
          echo "::set-output name=LatestRevision::$LatestRevision"

    - name: ECHO previous REVISION
      if: steps.first-deployment.outputs.FirstDeployment != false
      run: |
        echo "LatestRevision=$LatestRevision"      

      # Deploy Bicep file (existing cluster)
    - name: deploy
      #if: github.event.inputs.SKIP_INFRA == 'No'
      uses: azure/arm-deploy@v1
      if: steps.first-deployment.outputs.FirstDeployment != false
      id: deploy
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
        template: deploy/bicep/container-app.bicep
        parameters: image=${{env.ACR_REPO}}:${{ github.event.inputs.IMAGE_TAG }} acrPassword=${{ secrets.ACR_PASSWORD }}  newRevisionNumber=${{ github.run_number }} existingRevisionName=${{env.LatestRevision}}
        failOnStdErr: false
    
     # Deploy Bicep file (new cluster)
    - name: deploy NEW
      #if: github.event.inputs.SKIP_INFRA == 'No'
      uses: azure/arm-deploy@v1
      if: steps.first-deployment.outputs.FirstDeployment == false
      id: deploy-new
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
        template: deploy/bicep/container-app-new.bicep
        parameters: image=${{env.ACR_REPO}}:${{ github.event.inputs.IMAGE_TAG }} acrPassword=${{ secrets.ACR_PASSWORD }}  newRevisionNumber=${{ github.run_number }}
        failOnStdErr: false

    
    

  # check GREEN deployment and witch with BLUE if working
  switch-blue-green:
    name: switch BLUE/GREEN deployment
    runs-on: ubuntu-latest
    needs: deploy-azure-green
    if: needs.deploy-azure-green.outputs.FirstDeployment != false
    environment:
      name: ACA
    
    steps:

    # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: ECHO REVISION
      run: echo ${{ needs.deploy-azure-green.outputs.LatestRevision }}

    # only deactivate when another revision exists (after first deployment)
    - name: Replace the BLUE/GREEN traffic and deactivate old version
      uses: azure/CLI@v1
      with:
        azcliversion: 2.35.0
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az containerapp ingress traffic set --name $ACA_NAME -g $RG --traffic-weight latest=100
          az containerapp revision deactivate --revision ${{ needs.deploy-azure-green.outputs.LatestRevision }}  --resource-group $RG