#
# Deploy to Azure Kubernetes Service
# Using Helm for parameterized deployment
#

name: CD infra

on:
  workflow_dispatch:
    inputs:
      SKIP_INFRA:
        description: "Skip infrastructure deployment in manual triggers"
        required: false
        default: "No"
  # workflow_run:
  #   workflows:
  #     - "CI Build App"
  #   types:
  #   - completed

# Note. Required secrets: CLUSTER_KUBECONFIG

env:
  CLUSTER_NAME: srewithazureunai-aks-unai
  LOCATION: westeurope
  ACR_NAME: srewithazureunai 
  RG: srewithazureunai
  # INGRESS_DNS_HOST: dotnet-demoapp.kube.benco.io
  # AD_CLIENT_ID: 3584ac39-1ab1-4fe6-a3dd-4b2fbedc9d7d

jobs:
  #
  # Deploy AKS
  #
  deploy-azure:
    name: Deploy infrastructure to Azure Resource Group
    runs-on: ubuntu-latest
    # environment:
    #   name: AKS
    steps:

    # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      if: github.event.inputs.SKIP_INFRA == 'No'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
        template: deploy/bicep/main.bicep
        parameters: resourceName=${{env.CLUSTER_NAME}} location=${{env.LOCATION}} dnsPrefix=${{env.CLUSTER_NAME}}-dns workspaceName=${{env.CLUSTER_NAME}}-la acrName=${{env.ACR_NAME}} acrResourceGroup=${{env.RG}}
        failOnStdErr: false
    # Attach ACR to AKS cluster (DO MANUAL, IT FAILS FOR SOME REASON)
    - name: Azure CLI script
      run:
          az aks update -n $CLUSTER_NAME -g $RG --attach-acr $ACR_NAME

