name: CI Build App

on:
  push:
    branches: 
      - master 
      - 'feature/**'
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/ci-build.yaml"
  pull_request:
  workflow_dispatch:
    
    

env:
  IMAGE_REG: ${{ secrets.REGISTRY_LOGIN_SERVER }}
  IMAGE_REPO: dotnet6

jobs:
  test:
    name: "Tests & Linting"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      # - name: "Run linting"
      #   # We have to update the path because HOME is set weird in actions runner
      #   run: export PATH=$PATH:$HOME/.dotnet/tools && make lint

      - name: "Run tests"
        run: make test-report

      - name: "Upload test results"
        uses: actions/upload-artifact@v2
        # Disabled when running locally with the nektos/act tool
        if: ${{ always() }}
        with:
          name: test-results
          path: tests/TestResults/

      - name: "Publish test results"
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          files: tests/TestResults/TestResults.xml

  build:
    name: "Build & Push Image"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      # Nicer than using github runid, I think, will be picked up automatically by make
      - name: "Create datestamp image tag"
        run: echo "IMAGE_TAG=$(date +%d-%m-%Y.%H%M)" >> $GITHUB_ENV

      # Replace tokens in Dockerfile
      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '__'
          tokenSuffix: '__'
          files: '["**/Dockerfile"]'
        env:
          SP_AZURE_TENANT_ID: ${{ secrets.SP_AZURE_TENANT_ID }}
          SP_AZURE_CLIENT_ID: ${{ secrets.SP_AZURE_CLIENT_ID }}
          SP_AZURE_CLIENT_SECRET: ${{ secrets.SP_AZURE_CLIENT_SECRET }}  
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: "Docker build image"
        run: make image

      # Only when pushing to default branch (e.g. master or main), then push image to registry
      - name: Push to container registry
        # if: github.ref == 'refs/heads/master' && github.event_name == 'push' 
        run:  make push

      # - name: "Trigger AKS release pipeline"
      #   if: github.ref == 'refs/heads/master'
      #   uses: benc-uk/workflow-dispatch@v1
      #   with:
      #     workflow: "CD infra"
      #     token: ${{ secrets.GH_PAT }}
      #     # inputs: '{ "IMAGE_TAG": "${{ env.IMAGE_TAG }}" }'

      - name: "Trigger ACA release pipeline"
        if: github.ref == 'refs/heads/master'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "CD ACA"
          inputs: '{ "IMAGE_TAG": "${{ env.IMAGE_TAG }}" }'
      


