name: Trigger auto deployment for containerapp srewithazure-containerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    # branches: 
    #   [ master ]
    # paths:
    # - '**'
    # - '.github/workflows/srewithazure-containerapp-AutoDeployTrigger-a59f6d09-f3f3-42a0-aa64-4f03d6b447ea.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: srewithazure.azurecr.io
          username: ${{ secrets.SREWITHAZURECONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.SREWITHAZURECONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: srewithazure.azurecr.io/srewithazure-containerapp:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SREWITHAZURECONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n srewithazure-containerapp -g srewithazure --server srewithazure.azurecr.io --username  ${{ secrets.SREWITHAZURECONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.SREWITHAZURECONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n srewithazure-containerapp -g srewithazure --image srewithazure.azurecr.io/srewithazure-containerapp:${{ github.sha }}
